packages:
  - './'
  - './docs'
  - './playground'
catalog:
  '@iconify-json/lucide': ^1.2.124
  '@iconify-json/simple-icons': ^1.2.93
  '@iconify-json/vscode-icons': ^1.2.74
  '@nuxt/content': ^3.15.2
  '@nuxt/eslint': ^1.17.0
  '@nuxt/image': ^1.11.0
  '@nuxt/ui-pro': ^3.3.7
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/context-async-hooks': ^2.10.0
  '@opentelemetry/instrumentation': ^0.221.0
  '@opentelemetry/instrumentation-http': ^0.221.0
  '@opentelemetry/instrumentation-undici': ^0.31.0
  '@opentelemetry/sdk-trace-node': ^2.10.0
  '@opentelemetry/semantic-conventions': ^1.43.0
  '@types/node': ^24.13.3
  '@vitest/coverage-v8': ^4.1.11
  '@vitest/ui': ^4.1.11
  applicationinsights: ^3.16.0
  changelogen: ^0.6.2
  defu: ^6.1.7
  eslint: 10.8.1
  eslint-config-unjs: ^0.6.2
  jiti: ^2.7.0
  magic-string: ^1.2.1
  mlly: ^1.8.2
  nitro-opentelemetry: ^0.10.3
  nitro-test-utils: ^0.11.2
  nitropack: 2.13.4
  nuxt: ^4.5.2
  nuxt-llms: 0.2.0
  nuxt-og-image: ^6.7.8
  ofetch: ^1.5.1
  pathe: ^2.0.3
  rollup: ^4.62.4
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vitest: ^4.1.11
  vue-tsc: ^3.3.10
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
overrides:
  'electron-to-chromium': 1.5.411