packages:
  - './'
  - './docs'
  - './playground'
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
overrides:
  'electron-to-chromium': 1.5.400